### ISSUE TITLE
Error in bhat1^2 : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by krishnaxamin** [zhenin/HDL#33]
Hi! My issue is seemingly quite simple. Here's the complete output I get.

```
Analysis starts on Fri Apr 26 13:18:50 2024 
0 SNPs were removed in GWAS 1 due to missing N or missing test statistic.  
0 SNPs were removed in GWAS 2 due to missing N or missing test statistic.  
1029876 out of 1029876 (100%) SNPs in reference panel are available in GWAS 1.  
1029876 out of 1029876 (100%) SNPs in reference panel are available in GWAS 2.  
Error in bhat1^2 : non-numeric argument to binary operator
In addition: Warning messages:
1: There was 1 warning in `filter()`.
ℹ In argument: `SNP == SNP[duplicated(SNP)]`.
Caused by warning in `SNP == SNP[duplicated(SNP)]`:
! longer object length is not a multiple of shorter object length 
2: There was 1 warning in `filter()`.
ℹ In argument: `SNP == SNP[duplicated(SNP)]`.
Caused by warning in `SNP == SNP[duplicated(SNP)]`:
! longer object length is not a multiple of shorter object length 
```

I've looked through HDL.rg.R and see, from line 320 onwards:
```
M <- length(LDsc)
bhat1 <- bhat2 <- numeric(M)
names(bhat1) <- names(bhat2) <- snps.ref
bhat1[names(bhat1.raw)] <- bhat1.raw
bhat2[names(bhat2.raw)] <- bhat2.raw
        
a11 <- bhat1**2
```

I assume there's some error with LDsc but I cannot find where that comes from in the script. Please advise! Thanks!

P.S. Can I also check that we should use summary statistics for all variants tested, not just those significantly associated with the trait?

**Comment by now2014** [comment]
What are the structures of your two GWAS summary statistics? The error message shows that the `bhat1` variable is non-numeric, which equals GWAS z-scores divided by the square root of GWAS sample size (N).

Sure, all variants of the summary statistics should be used as the input, not just the significant variants.
`HDL` will intersect all input variants with variants in the LD reference panel automatically, and use the matched variants for analysis.

**Comment by krishnaxamin** [comment]
Thanks for the reply, and the clarification.

The data structures I pass into HDL.rg are nx6 data frames, with the columns:

- SNP
- A1
- A2
- N
- b
- se

in that order. Is there maybe an issue with calculating z-scores from b and se? All values in those two columns are numeric and there are no NA.

**Comment by now2014** [comment]
Glad to help. I need to check if it is a bug or not. Could you please show me the output of the `summary` function?

```R
summary(gwas.df1)
summary(gwas.df2)
```

Besides that, you can try running the data wrangling step (refer to [this wiki page](https://github.com/zhenin/HDL/wiki/Format-of-summary-statistics)) before `HDL.rg`.

**Comment by krishnaxamin** [comment]
Sure - here they are:
```
> summary(gwas1.df)
     SNP                 A1                 A2                  N                b                    se         
 Length:9878867     Length:9878867     Length:9878867     Min.   :423223   Min.   :-0.5873540   Min.   :0.01910  
 Class :character   Class :character   Class :character   1st Qu.:423223   1st Qu.:-0.0269362   1st Qu.:0.02733  
 Mode  :character   Mode  :character   Mode  :character   Median :423223   Median : 0.0000789   Median :0.03649  
                                                          Mean   :423223   Mean   : 0.0001714   Mean   :0.04890  
                                                          3rd Qu.:423223   3rd Qu.: 0.0271451   3rd Qu.:0.06274  
                                                          Max.   :423223   Max.   : 0.7489610   Max.   :0.22493  
```

```
> summary(gwas2.df)
     SNP                 A1                 A2                  N                b                    se         
 Length:9878876     Length:9878876     Length:9878876     Min.   :423223   Min.   :-0.7989140   Min.   :0.01900  
 Class :character   Class :character   Class :character   1st Qu.:423223   1st Qu.:-0.0264066   1st Qu.:0.02690  
 Mode  :character   Mode  :character   Mode  :character   Median :423223   Median : 0.0002111   Median :0.03594  
                                                          Mean   :423223   Mean   : 0.0003935   Mean   :0.04815  
                                                          3rd Qu.:423223   3rd Qu.: 0.0269434   3rd Qu.:0.06177  
                                                          Max.   :423223   Max.   : 0.7560130   Max.   :0.21834 
```

I will have a go at using the data wrangling step and let you know if that works. Thanks!

**Comment by now2014** [comment]
Thanks for your report!
It's a bug related to duplicated SNP IDs and I've just fixed it. You may need to update `HDL`.
To install the newest version of `HDL`:
```R
devtools::install_github('zhenin/HDL/HDL')
```
Please let me know if it works or not after the update.

**Comment by krishnaxamin** [comment]
Thanks! Unfortunately, the error persists, although the below warning messages have disappeared: 

```
In addition: Warning messages:
1: There was 1 warning in `filter()`.
ℹ In argument: `SNP == SNP[duplicated(SNP)]`.
Caused by warning in `SNP == SNP[duplicated(SNP)]`:
! longer object length is not a multiple of shorter object length 
2: There was 1 warning in `filter()`.
ℹ In argument: `SNP == SNP[duplicated(SNP)]`.
Caused by warning in `SNP == SNP[duplicated(SNP)]`:
! longer object length is not a multiple of shorter object length 
```

I stepped through the code using my gwas1.df and found that `row.remove` (line 287) was an empty integer, which meant that `gwas1.df.subset <- gwas1.df.subset[-row.remove,] %>% distinct(SNP, .keep_all = TRUE)` returned an empty dataframe: probably not intended? `row.remove` was empty in my case because all the duplicated SNPs flagged were due to REF/ALT reversals (for some reason, the order differed between genotyped and imputed results), so checking against `SNP_A1_A2.valid` returned nothing to be removed.

I fixed it below:

```
## Check if there are multiallelic or duplicated SNPs
    if(any(duplicated(gwas1.df.subset$SNP)) == TRUE){
      gwas1.df.subset.duplicated <- gwas1.df.subset %>% 
        mutate(row.num = 1:n()) %>% 
        filter(SNP %in% gwas1.df.subset$SNP[duplicated(gwas1.df.subset$SNP)]) %>%
        mutate(SNP_A1_A2 = paste(SNP, A1, A2, sep = "_"))
      snps.ref.df.duplicated <- snps.ref.df %>%
        filter(id %in% gwas1.df.subset.duplicated$SNP)
      SNP_A1_A2.valid <- c(paste(snps.ref.df.duplicated$id, snps.ref.df.duplicated$A1, snps.ref.df.duplicated$A2, sep = "_"),
                           paste(snps.ref.df.duplicated$id, snps.ref.df.duplicated$A2, snps.ref.df.duplicated$A1, sep = "_"))
      row.remove <- gwas1.df.subset.duplicated %>% filter(!(SNP_A1_A2 %in% SNP_A1_A2.valid)) %>% select(row.num) %>% unlist()
      if (length(row.remove) != 0){
        gwas1.df.subset <- gwas1.df.subset[-row.remove,] %>% distinct(SNP, .keep_all = TRUE)
      } else {
        gwas1.df.subset <- gwas1.df.subset %>% distinct(SNP, .keep_all = TRUE)
      }
    }

```

I then got this error out: 
```
Error in names(bhat1.raw) <- names(A2.gwas1) <- gwas1.df.subset$SNP : 
  'names' attribute [16972] must be the same length as the vector [1]
```
and fixed it below (to match with lines 271-273): 

```
    bhat1.raw <- (gwas1.df.subset[, "Z"] / sqrt(gwas1.df.subset[, "N"]))$Z
    A2.gwas1 <- gwas1.df.subset[, "A2"]$A2
    names(bhat1.raw) <- names(A2.gwas1) <- gwas1.df.subset$SNP 
```

Now `a11 <- bhat1**2` (line 323) works with no error.

I think the error arose before because `row.remove` was an empty integer, making `gwas1.df.subset` empty, making `bhat1.raw` a 0x1 dataframe. `bhat1` ended up being a list with every element = 0, and so the error occurred.

What do you think?

**Comment by now2014** [comment]
Yes, you're correct! The `row.remove` should be checked and I'll update the code.

Many thanks for your helpful inspection!

**Comment by krishnaxamin** [comment]
Thanks! I still have an error though: 
```
Error in names(bhat1.raw) <- names(A2.gwas1) <- gwas1.df.subset$SNP : 
  'names' attribute [16972] must be the same length as the vector [1]
```
 which I mentioned in my previous comment. Could you fix that as well, please? Thank you!

**Comment by now2014** [comment]
Sorry, I didn't notice that error the day before. I guess it's a compatibility issue related to `tibble`. Is your input GWAS a basic `data.frame` class?

Anyway, I've fixed it with the `$` operator.

Thanks!

**Comment by krishnaxamin** [comment]
I think it's a `tibble` - I read it in using `read_tsv`. In any case, thank you for your help and being so responsive! Appreciate it.
